# Generated by Django 3.0.2 on 2020-02-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cname', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Category')),
            ],
        ),
    ]
