# Generated by Django 3.0.2 on 2020-02-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.User')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Product')),
            ],
        ),
    ]
